version: '3.8'

services:
  client:
    image: client-dev-i
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./apps/client/src:/project/apps/client/src
    ports:
      - 3000:5173
    environment:
      - NODE_ENV=development