version: '3.8'

services:
  client:
    image: client-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: client-prod
    ports:
      - 3000:80
    environment:
      - NODE_ENV=production