FROM node:20-alpine AS base
WORKDIR /client
RUN npm i -g pnpm && pnpm setup
RUN pnpm i -g turbo
COPY . .
RUN turbo prune client --docker

FROM base AS prod
WORKDIR /client
COPY --from=base /app/out/json/ .
COPY --from=base /app/out/pnpm-lock.yaml pnpm-lock.yaml
RUN pnpm install

COPY --from=base /app/out/full/ .
RUN pnpm build

FROM nginx
COPY --from=prod /client/dist /usr/share/nginx/html